### ISSUE TITLE
1.20 Support

### ISSUE THREAD

**Issue by hkkongou** [Folium-MC/Residence-Maven#3]
Hi, i got the following error
i am using folia 1.20
Not sure am i compiling the plugin wrong, i am a newbie, if is in this case, can you provide a compiled jar of cmilib and residence for folia? thx
full log:
https://paste.denizenscript.com/View/111180

```
[11:50:45 ERROR]: [com.bekvon.bukkit.residence.Residence] null
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.getType()" because "this.item" is null
        at net.Zrips.CMILib.Items.CMIItemStack.getItemStack(CMIItemStack.java:388) ~[CMILib1.2.5.4.jar:?]
        at com.bekvon.bukkit.residence.gui.FlagUtil.load(FlagUtil.java:69) ~[Residence-folia.jar:?]
        at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:511) ~[Residence-folia.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[folia-api-1.20-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[folia-1.20.jar:git-Folia-"23b6f9e"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[folia-1.20.jar:git-Folia-"23b6f9e"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[folia-api-1.20-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:639) ~[folia-1.20.jar:git-Folia-"23b6f9e"]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:550) ~[folia-1.20.jar:git-Folia-"23b6f9e"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:681) ~[folia-1.20.jar:git-Folia-"23b6f9e"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:465) ~[folia-1.20.jar:git-Folia-"23b6f9e"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[folia-1.20.jar:git-Folia-"23b6f9e"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1190) ~[folia-1.20.jar:git-Folia-"23b6f9e"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:348) ~[folia-1.20.jar:git-Folia-"23b6f9e"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by lRENyaaa** [comment]
由于目前1.20下的Folia API仍处于不可用的状态,我暂时无法完成对Folia1.20的支持

Due to the current unavailability of the Folia API for 1.20, I am temporarily unable to complete the support for Folia 1.20.

**Comment by lRENyaaa** [comment]
Fixed in https://github.com/Folium-MC/Residence-Maven/commit/0afe009604e1b4072314b46c8c2dc933a401cbf1 and https://github.com/Folium-MC/CMILib/commit/a4e7209757e95756be6dfe9136eb2cfd9c982802
