### ISSUE TITLE
[bug]/resadmin server cannot use

### ISSUE THREAD

**Issue by cgw2023** [Folium-MC/Residence-Maven#5]
when use command /resadmin server <claimname>
error occur

```
[21:00:01] [Region Scheduler Thread #1/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'resadmin' in plugin Residence v5.1.1.3-Folia
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[folia-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[folia-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1040) ~[folia-1.20.1.jar:git-Folia-"fa018cc"]
	at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[folia-1.20.1.jar:git-Folia-"fa018cc"]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[folia-1.20.1.jar:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:324) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:308) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2326) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$16(ServerGamePacketListenerImpl.java:2286) ~[?:?]
	at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:173) ~[folia-1.20.1.jar:git-Folia-"fa018cc"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1524) ~[folia-1.20.1.jar:git-Folia-"fa018cc"]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:360) ~[folia-1.20.1.jar:git-Folia-"fa018cc"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[folia-1.20.1.jar:git-Folia-"fa018cc"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.1.jar:git-Folia-"fa018cc"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: UUID id cannot be null
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.1-jre.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.getPlayer(CraftServer.java:708) ~[folia-1.20.1.jar:git-Folia-"fa018cc"]
	at org.bukkit.Bukkit.getPlayer(Bukkit.java:720) ~[folia-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at com.bekvon.bukkit.residence.containers.ResidencePlayer.updatePlayer(ResidencePlayer.java:299) ~[Residence-Folia.jar:?]
	at com.bekvon.bukkit.residence.containers.ResidencePlayer.getName(ResidencePlayer.java:379) ~[Residence-Folia.jar:?]
	at com.bekvon.bukkit.residence.protection.PlayerManager.addPlayer(PlayerManager.java:36) ~[Residence-Folia.jar:?]
	at com.bekvon.bukkit.residence.protection.PlayerManager.playerJoin(PlayerManager.java:78) ~[Residence-Folia.jar:?]
	at com.bekvon.bukkit.residence.protection.PlayerManager.getResidencePlayer(PlayerManager.java:306) ~[Residence-Folia.jar:?]
	at com.bekvon.bukkit.residence.protection.ResidencePermissions.setOwner(ResidencePermissions.java:691) ~[Residence-Folia.jar:?]
	at com.bekvon.bukkit.residence.commands.server.perform(server.java:36) ~[Residence-Folia.jar:?]
	at com.bekvon.bukkit.residence.ResidenceCommandListener.onCommand(ResidenceCommandListener.java:275) ~[Residence-Folia.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[folia-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	... 14 more
```

https://mclo.gs/TiIp7Oc

**Comment by lRENyaaa** [comment]
官方版本已经支持folia,这个issue不再有用
