### ISSUE TITLE
[bug] error occur when claim InfoTool is used

### ISSUE THREAD

**Issue by cgw2023** [Folium-MC/Residence-Maven#6]
when claimtool is used to get info of a claim, error occurs
```
[21:11:46] [Region Scheduler Thread #0/ERROR]: Could not pass event PlayerInteractEvent to Residence v5.1.1.3-Folia
java.lang.IllegalArgumentException: UUID id cannot be null
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.1-jre.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.getPlayer(CraftServer.java:708) ~[folia-1.20.1.jar:git-Folia-"fa018cc"]
	at org.bukkit.Bukkit.getPlayer(Bukkit.java:720) ~[folia-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at com.bekvon.bukkit.residence.containers.ResidencePlayer.updatePlayer(ResidencePlayer.java:299) ~[Residence-Folia.jar:?]
	at com.bekvon.bukkit.residence.containers.ResidencePlayer.getName(ResidencePlayer.java:379) ~[Residence-Folia.jar:?]
	at com.bekvon.bukkit.residence.protection.PlayerManager.addPlayer(PlayerManager.java:36) ~[Residence-Folia.jar:?]
	at com.bekvon.bukkit.residence.protection.PlayerManager.playerJoin(PlayerManager.java:78) ~[Residence-Folia.jar:?]
	at com.bekvon.bukkit.residence.protection.PlayerManager.getResidencePlayer(PlayerManager.java:306) ~[Residence-Folia.jar:?]
	at com.bekvon.bukkit.residence.protection.ClaimedResidence.getRPlayer(ClaimedResidence.java:2029) ~[Residence-Folia.jar:?]
	at com.bekvon.bukkit.residence.protection.ClaimedResidence.getOwnerGroup(ClaimedResidence.java:2033) ~[Residence-Folia.jar:?]
	at com.bekvon.bukkit.residence.protection.ClaimedResidence.getWorthByOwner(ClaimedResidence.java:2211) ~[Residence-Folia.jar:?]
	at com.bekvon.bukkit.residence.protection.ResidenceManager.printAreaInfo(ResidenceManager.java:811) ~[Residence-Folia.jar:?]
	at com.bekvon.bukkit.residence.listeners.ResidencePlayerListener.onInfoCheck(ResidencePlayerListener.java:1297) ~[Residence-Folia.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor195.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[folia-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[folia-api-1.20.1-R0.1-SNAPSHOT.jar:git-Folia-"fa018cc"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[folia-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[folia-1.20.1.jar:git-Folia-"fa018cc"]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[folia-1.20.1.jar:git-Folia-"fa018cc"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[folia-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:564) ~[folia-1.20.1.jar:git-Folia-"fa018cc"]
	at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:521) ~[folia-1.20.1.jar:git-Folia-"fa018cc"]
	at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:516) ~[folia-1.20.1.jar:git-Folia-"fa018cc"]
	at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:511) ~[folia-1.20.1.jar:git-Folia-"fa018cc"]
	at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:199) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1899) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:52) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:75) ~[?:?]
	at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:173) ~[folia-1.20.1.jar:git-Folia-"fa018cc"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1524) ~[folia-1.20.1.jar:git-Folia-"fa018cc"]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:360) ~[folia-1.20.1.jar:git-Folia-"fa018cc"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[folia-1.20.1.jar:git-Folia-"fa018cc"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.1.jar:git-Folia-"fa018cc"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

https://mclo.gs/sD8Cm8f

**Comment by lRENyaaa** [comment]
官方版本已经支持folia,这个issue不再有用
